// The worker needs the word list too -- to validate what it is given, and to
// build the neighbours a repair searches. Generated from the one file that is
// the source of truth, with its hash carried along so a drift is loud.
import { readFileSync, writeFileSync } from 'node:fs';
import { createHash } from 'node:crypto';
import { dirname, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const src = join(here, '..', '..', '..', 'tools', 'wordlist', 'spoken-1296-plain.txt');
const raw = readFileSync(src);
const sha = createHash('sha256').update(raw).digest('hex');
const words = raw.toString().split('\n').filter(Boolean);
if (words.length !== 1296) throw new Error(`expected 1296 words, got ${words.length}`);

const out = `// GENERATED by tools/gen-words.mjs from tools/wordlist/spoken-1296-plain.txt
// Do not edit. Run \`npm run words\` to regenerate; \`npm test\` fails if it drifts.
export const WORDLIST_SHA256 = '${sha}';
export const WORDS = ${JSON.stringify(words)};
export const INDEX = new Map(WORDS.map((w, i) => [w, i]));
`;
writeFileSync(join(here, '..', 'src', 'words.js'), out);
console.log(`wrote src/words.js -- ${words.length} words, sha256 ${sha.slice(0, 12)}...`);
