// The demo carries its own JavaScript port of the codec. This runs that port
// against a fixture generated by the Python reference, so the two cannot drift.
// Regenerate with tools/gridcode/build_fixture.py after any change.
import { readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { fileURLToPath, pathToFileURL } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, '..', '..', 'demos', 'word-grid.html'), 'utf8');
const fixture = JSON.parse(readFileSync(join(here, 'fixture.json'), 'utf8'));

const words = html.match(/const WORDS = (\[[^\n]*\]);/)[1];
const start = html.indexOf('const INDEX = new Map');
const end = html.indexOf('// --- map ---');
const src = `const WORDS = ${words};\n${html.slice(start, end)}\n`
  + 'export { encode, decode, resolveTail, wordsNeeded, cellSize, tileSize,'
  + ' indices, parseAddress, formatAddress, ORDER, XB, YB };';
// Written to a real file rather than a data: URL: the extracted module is
// ~30 KB and a data: URL of that size fails to import with the URL itself as
// the message, which is not a debuggable error.
const tmp = join(tmpdir(), `word-grid-check-${process.pid}.mjs`);
writeFileSync(tmp, src);
let mod;
try { mod = await import(pathToFileURL(tmp).href); } finally { rmSync(tmp, { force: true }); }

let bad = 0;
const fail = (msg) => { bad++; console.error(`  ${msg}`); };

// The bit order decides the shape of every cell, so the two ports must agree
// on it exactly, not merely on the totals.
const order = mod.ORDER.map((a) => 'xy'[a]).join('');
if (order !== fixture.order) fail(`bit order: js ${order} vs py ${fixture.order}`);
if (mod.XB !== fixture.axis_bits[0] || mod.YB !== fixture.axis_bits[1])
  fail(`axis bits: js ${[mod.XB, mod.YB]} vs py ${fixture.axis_bits}`);

for (const c of fixture.points) {
  for (const [n, expected] of Object.entries(c.words)) {
    const got = mod.encode(c.lat, c.lng, Number(n));
    if (got.join('.') !== expected.join('.'))
      fail(`MISMATCH ${c.lat},${c.lng} @${n}: js ${got.join('.')} vs py ${expected.join('.')}`);
    const [lat, lng] = mod.decode(expected);
    if (!Number.isFinite(lat) || !Number.isFinite(lng))
      fail(`BAD DECODE ${expected.join('.')}`);
  }
  // truncation: every length must be a prefix of the longest
  const longest = c.words[String(Object.keys(c.words).length)];
  for (const [n, expected] of Object.entries(c.words))
    if (longest.slice(0, Number(n)).join('.') !== expected.join('.'))
      fail(`NOT A PREFIX at ${n}: ${expected.join('.')}`);
  // the full address must pass its own embedded checksum
  try { mod.decode(longest); }
  catch (e) { fail(`CHECKSUM ${c.lat},${c.lng}: ${e.message}`); }
}

// Dropping leading words and filling them back in from a reference point,
// including across the antimeridian where x has to wrap.
for (const t of fixture.tails) {
  let got;
  try { got = mod.resolveTail(t.words, t.ref[0], t.ref[1]); }
  catch (e) { fail(`TAIL .${t.words.join('.')} from ${t.ref}: ${e.message}`); continue; }
  const a = mod.indices(got[0], got[1]), b = mod.indices(t.resolved[0], t.resolved[1]);
  if (a[0] !== b[0] || a[1] !== b[1])
    fail(`TAIL .${t.words.join('.')} from ${t.ref}: js ${got} vs py ${t.resolved}`);
}

// A reference too far away to pick the right tile must be refused, not
// resolved quietly to the wrong place.
for (const h of fixture.hopeless) {
  let refused = false;
  try {
    const got = mod.resolveTail(h.words, h.ref[0], h.ref[1]);
    refused = !Number.isFinite(got[0]);
  } catch { refused = true; }
  if (!refused) fail(`RESOLVED a hopeless tail .${h.words.join('.')} from ${h.ref}`);
}

// The leading separator is the whole notation for a tail, so parsing it back
// has to survive the round trip in both ports.
for (const [text, n, tail] of [['leg.tunnel.slam', 3, false],
                               ['.slam.subway.gown', 3, true],
                               ['  LEG tunnel Slam ', 3, false]]) {
  const [parts, isTail] = mod.parseAddress(text);
  if (parts.length !== n || isTail !== tail)
    fail(`PARSE ${JSON.stringify(text)} -> ${parts.length} words, tail=${isTail}`);
}

console.log(`demo codec vs python reference: ${fixture.points.length} points x `
  + `${Object.keys(fixture.points[0].words).length} lengths, `
  + `${fixture.tails.length} tails, ${fixture.hopeless.length} hopeless`);
if (bad) { console.error(`FAIL: ${bad} problem(s)`); process.exit(1); }
console.log('OK: codecs agree, truncation holds, checksums verify, tails resolve');
