// The demo carries its own JavaScript port of the codec. This runs that port
// against a fixture generated by the Python reference, so the two cannot drift.
// Regenerate with tools/gridcode/build_fixture.py after any change.
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const html = readFileSync(join(here, '..', '..', 'demos', 'word-grid.html'), 'utf8');
const fixture = JSON.parse(readFileSync(join(here, 'fixture.json'), 'utf8'));

const words = html.match(/const WORDS = (\[[^\n]*\]);/)[1];
const start = html.indexOf('const INDEX = new Map');
const end = html.indexOf('// --- map ---');
const src = `const WORDS = ${words};\n${html.slice(start, end)}\nexport { encode, decode, covers };`;
const mod = await import('data:text/javascript,' + encodeURIComponent(src));

let bad = 0;
for (const c of fixture.points) {
  for (const [n, expected] of Object.entries(c.words)) {
    const got = mod.encode(c.lat, c.lng, Number(n));
    if (got.join('.') !== expected.join('.')) {
      bad++; console.error(`  MISMATCH ${c.lat},${c.lng} @${n}: js ${got.join('.')} vs py ${expected.join('.')}`);
    }
    // an address must resolve back into the cell it names
    const [lat, lng] = mod.decode(expected);
    const [w, h] = mod.cellSize ? mod.cellSize(Number(n)) : [1e9, 1e9];
    if (!Number.isFinite(lat) || !Number.isFinite(lng)) { bad++; console.error('  BAD DECODE', expected); }
  }
  // truncation: every length must be a prefix of the longest
  const longest = c.words[String(Object.keys(c.words).length)];
  for (const [n, expected] of Object.entries(c.words)) {
    if (longest.slice(0, Number(n)).join('.') !== expected.join('.')) {
      bad++; console.error(`  NOT A PREFIX at ${n}: ${expected.join('.')}`);
    }
  }
  // a four-word address must pass its own embedded checksum
  try { mod.decode(c.words[String(Object.keys(c.words).length)]); }
  catch (e) { bad++; console.error(`  CHECKSUM ${c.lat},${c.lng}: ${e.message}`); }
}
// Coverage must stop in the same place in both ports. An outside point that
// slipped through would be given an address belonging to somewhere inside the
// box, and would pass its own checksum.
for (const c of fixture.outside) {
  if (mod.covers(c.lat, c.lng)) {
    bad++; console.error(`  COVERS an outside point ${c.lat},${c.lng}`);
    continue;
  }
  let refused = false;
  try { mod.encode(c.lat, c.lng, 4); } catch { refused = true; }
  if (!refused) { bad++; console.error(`  ENCODED an outside point ${c.lat},${c.lng}`); }
}
console.log(`demo codec vs python reference: ${fixture.points.length} points x `
  + `${Object.keys(fixture.points[0].words).length} lengths, `
  + `${fixture.outside.length} outside refused`);
if (bad) { console.error(`FAIL: ${bad} problem(s)`); process.exit(1); }
console.log('OK: agrees with the reference, truncation holds, checksums verify, coverage matches');
